### ISSUE TITLE
sorting moves comments to the top

### ISSUE THREAD

**Issue by rafalkrupinski** [andrei-shabanski/poetry-plugin-sort#1]
Thank you for your effort making this plug-in :)

I found that comments in the dependency lists are moved to the top.
Typically comments would be temporarily disabled dependency or a explanation on the dependency directly below the comment.
I think making the comments stick to the next non-comment line would be good for the latter case and acceptable for the former.

Cheers

**Comment by andrei-shabanski** [comment]
I believed the original PR would be merged into Poetry before somebody notes this issue. Unfortunately, poetry authors still don't reach a consensus.

So I've made some changes, and now this issue should be fixed. I would be grateful if you install the latest version of the plugin and check it.

Thanks!

**Comment by rafalkrupinski** [comment]
Is the plugin compatible with the new [plugins](https://python-poetry.org/docs/pyproject/#plugins) pyproject entry?
