### ISSUE TITLE
[Bug] pyproject.toml is not being updated because of the plugin

### ISSUE THREAD

**Issue by roniemartinez** [andrei-shabanski/poetry-plugin-sort#15]
I am recently encountering issues wherein the `pyproject.toml` is not being updated despite calling `poetry add` on a new package. After investigating, I was able to find out that `poetry-plugin-sort` was causing it (by removing the plugin). Not sure why but maybe you could replicate and investigate. Thanks

```
$  git status    
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   poetry.lock

no changes added to commit (use "git add" and/or "git commit -a")
```

Here are my environment details:
```bash
$  sw_vers
ProductName:		macOS
ProductVersion:		14.2.1
BuildVersion:		23C71
$  pip list | grep poetry          
poetry               1.7.1
poetry-core          1.8.1
poetry-plugin-export 1.6.0
$ python -V             
Python 3.12.1
```

**Comment by andrei-shabanski** [comment]
@roniemartinez Could you please provide
* your pyproject.toml file
* the full command `poetry add ...` that you ran?

If you can reinstall the plugin, try to run `poetry add .. ` with the `-vvv` flag. I'm not sure that -vvv shows any stacktrace in case of an exception though

**Comment by roniemartinez** [comment]
I actually tried adding `-vvv` but nothing in there.

Here is my `pyproject.toml`
```toml
[tool.poetry]
name = "example"
version = "0.1.0"
description = ""
authors = ["Ronie Martinez <ronmarti18@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

And here is the output from the command:
```
poetry add django@latest -vvv
Creating virtualenv example-fOsKWhnX-py3.12 in /Users/roniemartinez/Library/Caches/pypoetry/virtualenvs
Using virtualenv: /Users/roniemartinez/Library/Caches/pypoetry/virtualenvs/example-fOsKWhnX-py3.12
Using version ^5.0 for django

Updating dependencies
Resolving dependencies...
   1: fact: example is 0.1.0
   1: derived: example
   1: fact: example depends on django (^5.0)
   1: selecting example (0.1.0)
   1: derived: django (>=5.0,<6.0)
   1: fact: django (5.0) depends on asgiref (>=3.7.0)
   1: fact: django (5.0) depends on sqlparse (>=0.3.1)
   1: fact: django (5.0) depends on tzdata (*)
   1: selecting django (5.0)
   1: derived: tzdata
   1: derived: sqlparse (>=0.3.1)
   1: derived: asgiref (>=3.7.0)
   1: selecting sqlparse (0.4.4)
   1: selecting asgiref (3.7.2)
   1: selecting tzdata (2023.4)
   1: Version solving took 0.024 seconds.
   1: Tried 1 solutions.

Finding the necessary packages for the current system

Package operations: 3 installs, 0 updates, 0 removals

  • Installing asgiref (3.7.2): Pending...
  • Installing asgiref (3.7.2): Installing...
  • Installing asgiref (3.7.2)
  • Installing sqlparse (0.4.4): Pending...
  • Installing sqlparse (0.4.4): Installing...
  • Installing sqlparse (0.4.4)
  • Installing django (5.0): Pending...
  • Installing django (5.0): Installing...
  • Installing django (5.0)

Writing lock file
Sorting items in [tool.poetry.dependencies].
Dependencies were sorted.
```

Only `poetry.lock` seems to be updated properly.

**Comment by andrei-shabanski** [comment]
I set up the same environment as you, but I didn't manage to reproduce the issue.

I did a little investigation, and poetry seems to save the pyproject.toml file before calling plugins.
I also deliberately added raising an exception inside the plugin. Even in that case `poetry add django` command installed django and added it into pyproject.toml and poetry.lock files. I saw the exception in the console though (-vvv showed the stacktrace as well).

**Comment by roniemartinez** [comment]
@andrei-shabanski Thanks for checking. I realized that I also installed another tool a few days ago called `poethepoet` (https://github.com/nat-n/poethepoet).

It looks like this tool interferes with this `poetry-plugin-sort` if they are installed together. Removing `poethepoet` works for me but just in case, not sure which one introduces the bug.

**Comment by andrei-shabanski** [comment]
Thank you for mentioning poethepoet. It turned out that the plugin read a toml document from a cached property, which can store outdated data. The fix has already been released.

**Comment by roniemartinez** [comment]
Thanks @andrei-shabanski 🚀 
The new update works well with poethepoet
