### ISSUE TITLE
Update poetry to latest version after `poetry update`

### ISSUE THREAD

**Issue by shpaker** [andrei-shabanski/poetry-plugin-sort#6]
After execution the `poetry update` command in repository with `poetry-plugin-sort` plugin in dependencies became unexpectedly the upper version  of poetry.

**Comment by andrei-shabanski** [comment]
Describe the issue in more detail, along with a sample of pyproject.toml file

**Comment by shpaker** [comment]
One of the dependencies group in my projects looks like:

```
[tool.poetry.group.dev.dependencies]
poetry-plugin-sort = "^0.1.1"
pre-commit = "^3.3.1"
...
```

**Comment by andrei-shabanski** [comment]
This plugin depends on the poetry package and can't work without it. Because of that poetry is listed in dependencies in setup.py

**Comment by shpaker** [comment]
🙄
