### ISSUE TITLE
`pre-commit` Hook Fails to Run

### ISSUE THREAD

**Issue by adam-grant-hendry** [andrei-shabanski/poetry-plugin-sort#8]
The `pre-commit` hook fails to run because [`SortDependenciesPlugin.sort_dependencies`](https://github.com/andrei-shabanski/poetry-plugin-sort/blob/5022cb898a649e13ed7b6244b54fe9116a976eeb/poetry_plugin_sort/plugins.py#L62) does not first check for `config.is_sorting_enabled(command.poetry)`.

**Comment by andrei-shabanski** [comment]
`enabled` config option impacts `poetry init / add` only. Whereas the hook executes `poetry sort` which, like the hook, operates in a straightforward manner and performs sorting regardless of any configurations

**Comment by adam-grant-hendry** [comment]
Thanks for the clarification.

**Comment by adam-grant-hendry** [comment]
@andrei-shabanski Oh I see. Just for posterity's-sake, when `poetry`'s `PluginManager` is `activate`d (either in `poetry/factory.py` or `poetry/console/application.py`), it [activates each plugin](https://github.com/python-poetry/poetry/blob/5fe3a913c0656b45049b109f45130119c1756a2d/src/poetry/plugins/plugin_manager.py#L69) in the ["poetry.application.plugin" group](https://github.com/python-poetry/poetry/blob/5fe3a913c0656b45049b109f45130119c1756a2d/src/poetry/plugins/application_plugin.py#L18) (see [python builtin `importlib.metadata`](https://docs.python.org/3.8/library/importlib.metadata.html#entry-points) for more). `ApplicationPlugin` instances take each `cleo` command listed in the [`commands` property](https://github.com/python-poetry/poetry/blob/5fe3a913c0656b45049b109f45130119c1756a2d/src/poetry/plugins/application_plugin.py#L21) and registers them into the [`application.command_loader`](https://github.com/python-poetry/poetry/blob/5fe3a913c0656b45049b109f45130119c1756a2d/src/poetry/plugins/application_plugin.py#L24).

Just wanted to point out that's why it's important to specifically list your `PluginCommand` in the `commands` property and to definitely use `"poetry.application.plugin"` when writing out your `pyproject.toml` (i.e. the table should read `[tool.poetry.plugins."poetry.application.plugin"]`).
